#ifndef MY_FIRST_VULKAN_ENGINE_DEFINITIONS_H
#define MY_FIRST_VULKAN_ENGINE_DEFINITIONS_H

// Defines
#define MFVE_ENGINE_NAME "my-first-vulkan-engine"
#define MFVE_VER_MAJOR   0
#define MFVE_VER_MINOR   1
#define MFVE_VER_PATCH   0

#endif // MY_FIRST_VULKAN_ENGINE_DEFINITIONS_H