project "Generate-Assets"

-- This project should by of kind "Utility". However, due to some issues with build commands the asset
-- generation is being done as a post build command - this requires a lib to be generated. This lib will 
-- automatically be deleted after this build and will allow this project to be re-built again and again.

    kind "StaticLib"

    targetdir (_apptargetdir)
    objdir    (_appobjdir)

    -- Post build command to generate assets (currently only moving them to target dir)
    postbuildcommands{
        "{ECHO} Generating Assets...",

        -- Copying assets directory to app target directory
        "{COPYDIR} " .. _assetdir .. " " .. _apptargetdir,

        -- Deleting lib file generated by this build
        '{ECHO} Deleting "%{cfg.buildtarget.name}" - this is expected behaviour!',
        "{DELETE} %{cfg.buildtarget.abspath}",

        "{ECHO} Finished Generating Assets"
    }