name: Linux Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        
    - name: Install Dependencies 
      run: |
        sudo apt update
        sudo apt-get install xorg-dev
        sudo apt-get install make
        sudo apt-get install shaderc
      
    - name: Setup Vulkan SDK
      uses: humbletim/setup-vulkan-sdk@v1.0.2

    - name: Install Premake
      uses: abel0b/setup-premake@v1
      
    - name: Setup Premake
      run: premake5 gmake2

    - name: Debug Build
      run: make config=debug all
      
    - name: Release Build
      run: make config=release all
