name: Linux Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
      
    - name: Install Premake
      uses: abel0b/setup-premake@v1
      
    - name: Setup Premake
      run: premake5 gmake2

    - name: Debug Build
      run: make config=debug all
      
    - name: Release Build
      run: make config=release all
